var data = {
    "United States": {
        "Total": 80,
        "American Indian/Alaska Native": 67,
        "Asian/Pacific Islander": 88,
        "Hispanic": 73,
        "Black": 69,
        "White": 86,
        "Economically disadvantaged": 72,
        "Limited English proficiency": 59,
        "Students with disabilities": 61
    },
    "Alabama": {
        "Total": 75,
        "American Indian/Alaska Native": 84,
        "Asian/Pacific Islander": 85,
        "Hispanic": 69,
        "Black": 67,
        "White": 81,
        "Economically disadvantaged": 66,
        "Limited English proficiency": 36,
        "Students with disabilities": 54
    },
    "Alaska": {
        "Total": 70,
        "American Indian/Alaska Native": 54,
        "Asian/Pacific Islander": 76,
        "Hispanic": 70,
        "Black": 61,
        "White": 76,
        "Economically disadvantaged": 59,
        "Limited English proficiency": 47,
        "Students with disabilities": 46
    },
    "Arizona": {
        "Total": 76,
        "American Indian/Alaska Native": 63,
        "Asian/Pacific Islander": 84,
        "Hispanic": 70,
        "Black": 71,
        "White": 84,
        "Economically disadvantaged": 71,
        "Limited English proficiency": 24,
        "Students with disabilities": 65
    },
    "Arkansas": {
        "Total": 84,
        "American Indian/Alaska Native": 78,
        "Asian/Pacific Islander": 84,
        "Hispanic": 78,
        "Black": 78,
        "White": 87,
        "Economically disadvantaged": 79,
        "Limited English proficiency": 77,
        "Students with disabilities": 79
    },
    "California": {
        "Total": 78,
        "American Indian/Alaska Native": 72,
        "Asian/Pacific Islander": 90,
        "Hispanic": 73,
        "Black": 66,
        "White": 86,
        "Economically disadvantaged": 73,
        "Limited English proficiency": 62,
        "Students with disabilities": 61
    },
    "Colorado": {
        "Total": 75,
        "American Indian/Alaska Native": 58,
        "Asian/Pacific Islander": 82,
        "Hispanic": 62,
        "Black": 66,
        "White": 82,
        "Economically disadvantaged": 61,
        "Limited English proficiency": 53,
        "Students with disabilities": 54
    },
    "Connecticut": {
        "Total": 85,
        "American Indian/Alaska Native": 84,
        "Asian/Pacific Islander": 92,
        "Hispanic": 69,
        "Black": 73,
        "White": 91,
        "Economically disadvantaged": 71,
        "Limited English proficiency": 63,
        "Students with disabilities": 64
    },
    "Delaware": {
        "Total": 80,
        "American Indian/Alaska Native": 71,
        "Asian/Pacific Islander": 93,
        "Hispanic": 74,
        "Black": 74,
        "White": 83,
        "Economically disadvantaged": 72,
        "Limited English proficiency": 71,
        "Students with disabilities": 57
    },
    "District of Columbia": {
        "Total": 59,
        "American Indian/Alaska Native": null,
        "Asian/Pacific Islander": 74,
        "Hispanic": 54,
        "Black": 58,
        "White": 86,
        "Economically disadvantaged": 70,
        "Limited English proficiency": 52,
        "Students with disabilities": 44
    },
    "Florida": {
        "Total": 75,
        "American Indian/Alaska Native": 70,
        "Asian/Pacific Islander": 89,
        "Hispanic": 73,
        "Black": 64,
        "White": 80,
        "Economically disadvantaged": 65,
        "Limited English proficiency": 57,
        "Students with disabilities": 48
    },
    "Georgia": {
        "Total": 70,
        "American Indian/Alaska Native": 67,
        "Asian/Pacific Islander": 82,
        "Hispanic": 60,
        "Black": 62,
        "White": 78,
        "Economically disadvantaged": 61,
        "Limited English proficiency": 44,
        "Students with disabilities": 35
    },
    "Hawaii": {
        "Total": 82,
        "American Indian/Alaska Native": 65,
        "Asian/Pacific Islander": 84,
        "Hispanic": 76,
        "Black": 76,
        "White": 79,
        "Economically disadvantaged": 80,
        "Limited English proficiency": 56,
        "Students with disabilities": 74
    },
    "Idaho": {
        "Total": null,
        "American Indian/Alaska Native": null,
        "Asian/Pacific Islander": null,
        "Hispanic": null,
        "Black": null,
        "White": null,
        "Economically disadvantaged": null,
        "Limited English proficiency": null,
        "Students with disabilities": null
    },
    "Illinois": {
        "Total": 82,
        "American Indian/Alaska Native": 79,
        "Asian/Pacific Islander": 93,
        "Hispanic": 76,
        "Black": 68,
        "White": 89,
        "Economically disadvantaged": 73,
        "Limited English proficiency": 66,
        "Students with disabilities": 69
    },
    "Indiana": {
        "Total": 86,
        "American Indian/Alaska Native": 78,
        "Asian/Pacific Islander": 89,
        "Hispanic": 80,
        "Black": 73,
        "White": 89,
        "Economically disadvantaged": 85,
        "Limited English proficiency": 78,
        "Students with disabilities": 71
    },
    "Iowa": {
        "Total": 89,
        "American Indian/Alaska Native": 73,
        "Asian/Pacific Islander": 89,
        "Hispanic": 77,
        "Black": 74,
        "White": 91,
        "Economically disadvantaged": 80,
        "Limited English proficiency": 74,
        "Students with disabilities": 73
    },
    "Kansas": {
        "Total": 85,
        "American Indian/Alaska Native": 78,
        "Asian/Pacific Islander": 86,
        "Hispanic": 77,
        "Black": 75,
        "White": 88,
        "Economically disadvantaged": 76,
        "Limited English proficiency": 74,
        "Students with disabilities": 77
    },
    "Kentucky": {
        "Total": null,
        "American Indian/Alaska Native": null,
        "Asian/Pacific Islander": null,
        "Hispanic": null,
        "Black": null,
        "White": null,
        "Economically disadvantaged": null,
        "Limited English proficiency": null,
        "Students with disabilities": null
    },
    "Louisiana": {
        "Total": 72,
        "American Indian/Alaska Native": 73,
        "Asian/Pacific Islander": 85,
        "Hispanic": 70,
        "Black": 65,
        "White": 78,
        "Economically disadvantaged": 66,
        "Limited English proficiency": 49,
        "Students with disabilities": 33
    },
    "Maine": {
        "Total": 85,
        "American Indian/Alaska Native": 72,
        "Asian/Pacific Islander": 89,
        "Hispanic": 80,
        "Black": 72,
        "White": 86,
        "Economically disadvantaged": 76,
        "Limited English proficiency": 74,
        "Students with disabilities": 70
    },
    "Maryland": {
        "Total": 84,
        "American Indian/Alaska Native": 79,
        "Asian/Pacific Islander": 93,
        "Hispanic": 73,
        "Black": 77,
        "White": 90,
        "Economically disadvantaged": 75,
        "Limited English proficiency": 55,
        "Students with disabilities": 57
    },
    "Massachusetts": {
        "Total": 85,
        "American Indian/Alaska Native": 70,
        "Asian/Pacific Islander": 89,
        "Hispanic": 66,
        "Black": 73,
        "White": 90,
        "Economically disadvantaged": 72,
        "Limited English proficiency": 61,
        "Students with disabilities": 69
    },
    "Michigan": {
        "Total": 76,
        "American Indian/Alaska Native": 66,
        "Asian/Pacific Islander": 87,
        "Hispanic": 64,
        "Black": 60,
        "White": 82,
        "Economically disadvantaged": 64,
        "Limited English proficiency": 63,
        "Students with disabilities": 54
    },
    "Minnesota": {
        "Total": 78,
        "American Indian/Alaska Native": 45,
        "Asian/Pacific Islander": 74,
        "Hispanic": 53,
        "Black": 51,
        "White": 84,
        "Economically disadvantaged": 59,
        "Limited English proficiency": 51,
        "Students with disabilities": 56
    },
    "Mississippi": {
        "Total": 75,
        "American Indian/Alaska Native": 71,
        "Asian/Pacific Islander": 90,
        "Hispanic": 79,
        "Black": 69,
        "White": 82,
        "Economically disadvantaged": 70,
        "Limited English proficiency": 54,
        "Students with disabilities": 32
    },
    "Missouri": {
        "Total": 86,
        "American Indian/Alaska Native": 87,
        "Asian/Pacific Islander": 90,
        "Hispanic": 80,
        "Black": 73,
        "White": 89,
        "Economically disadvantaged": 79,
        "Limited English proficiency": 67,
        "Students with disabilities": 73
    },
    "Montana": {
        "Total": 84,
        "American Indian/Alaska Native": 63,
        "Asian/Pacific Islander": 92,
        "Hispanic": 79,
        "Black": 79,
        "White": 87,
        "Economically disadvantaged": 73,
        "Limited English proficiency": 53,
        "Students with disabilities": 81
    },
    "Nebraska": {
        "Total": 88,
        "American Indian/Alaska Native": 67,
        "Asian/Pacific Islander": 83,
        "Hispanic": 78,
        "Black": 74,
        "White": 91,
        "Economically disadvantaged": 80,
        "Limited English proficiency": 64,
        "Students with disabilities": 72
    },
    "Nevada": {
        "Total": 63,
        "American Indian/Alaska Native": 54,
        "Asian/Pacific Islander": 74,
        "Hispanic": 54,
        "Black": 48,
        "White": 72,
        "Economically disadvantaged": 58,
        "Limited English proficiency": 23,
        "Students with disabilities": 24
    },
    "New Hampshire": {
        "Total": 86,
        "American Indian/Alaska Native": 73,
        "Asian/Pacific Islander": 86,
        "Hispanic": 74,
        "Black": 76,
        "White": 87,
        "Economically disadvantaged": 73,
        "Limited English proficiency": 68,
        "Students with disabilities": 70
    },
    "New Jersey": {
        "Total": 86,
        "American Indian/Alaska Native": 84,
        "Asian/Pacific Islander": 95,
        "Hispanic": 77,
        "Black": 75,
        "White": 93,
        "Economically disadvantaged": 75,
        "Limited English proficiency": 73,
        "Students with disabilities": 74
    },
    "New Mexico": {
        "Total": 70,
        "American Indian/Alaska Native": 65,
        "Asian/Pacific Islander": 84,
        "Hispanic": 68,
        "Black": 69,
        "White": 77,
        "Economically disadvantaged": 65,
        "Limited English proficiency": 66,
        "Students with disabilities": 56
    },
    "New York": {
        "Total": 77,
        "American Indian/Alaska Native": 63,
        "Asian/Pacific Islander": 86,
        "Hispanic": 63,
        "Black": 63,
        "White": 87,
        "Economically disadvantaged": 68,
        "Limited English proficiency": 44,
        "Students with disabilities": 48
    },
    "North Carolina": {
        "Total": 80,
        "American Indian/Alaska Native": 74,
        "Asian/Pacific Islander": 87,
        "Hispanic": 73,
        "Black": 75,
        "White": 85,
        "Economically disadvantaged": 75,
        "Limited English proficiency": 50,
        "Students with disabilities": 60
    },
    "North Dakota": {
        "Total": 87,
        "American Indian/Alaska Native": 63,
        "Asian/Pacific Islander": 86,
        "Hispanic": 73,
        "Black": 76,
        "White": 90,
        "Economically disadvantaged": 74,
        "Limited English proficiency": 68,
        "Students with disabilities": 68
    },
    "Ohio": {
        "Total": 81,
        "American Indian/Alaska Native": 65,
        "Asian/Pacific Islander": 90,
        "Hispanic": 68,
        "Black": 61,
        "White": 86,
        "Economically disadvantaged": 68,
        "Limited English proficiency": 62,
        "Students with disabilities": 68
    },
    "Oklahoma": {
        "Total": null,
        "American Indian/Alaska Native": null,
        "Asian/Pacific Islander": null,
        "Hispanic": null,
        "Black": null,
        "White": null,
        "Economically disadvantaged": null,
        "Limited English proficiency": null,
        "Students with disabilities": null
    },
    "Oregon": {
        "Total": 68,
        "American Indian/Alaska Native": 51,
        "Asian/Pacific Islander": 79,
        "Hispanic": 60,
        "Black": 53,
        "White": 71,
        "Economically disadvantaged": 61,
        "Limited English proficiency": 49,
        "Students with disabilities": 38
    },
    "Pennsylvania": {
        "Total": 84,
        "American Indian/Alaska Native": 74,
        "Asian/Pacific Islander": 89,
        "Hispanic": 68,
        "Black": 68,
        "White": 89,
        "Economically disadvantaged": 74,
        "Limited English proficiency": 64,
        "Students with disabilities": 70
    },
    "Rhode Island": {
        "Total": 77,
        "American Indian/Alaska Native": 58,
        "Asian/Pacific Islander": 79,
        "Hispanic": 67,
        "Black": 67,
        "White": 82,
        "Economically disadvantaged": 66,
        "Limited English proficiency": 69,
        "Students with disabilities": 59
    },
    "South Carolina": {
        "Total": 75,
        "American Indian/Alaska Native": 71,
        "Asian/Pacific Islander": 85,
        "Hispanic": 69,
        "Black": 71,
        "White": 78,
        "Economically disadvantaged": 68,
        "Limited English proficiency": 64,
        "Students with disabilities": 40
    },
    "South Dakota": {
        "Total": 83,
        "American Indian/Alaska Native": 47,
        "Asian/Pacific Islander": 84,
        "Hispanic": 67,
        "Black": 67,
        "White": 89,
        "Economically disadvantaged": 67,
        "Limited English proficiency": 60,
        "Students with disabilities": 64
    },
    "Tennessee": {
        "Total": 87,
        "American Indian/Alaska Native": 88,
        "Asian/Pacific Islander": 91,
        "Hispanic": 80,
        "Black": 79,
        "White": 91,
        "Economically disadvantaged": 82,
        "Limited English proficiency": 72,
        "Students with disabilities": 73
    },
    "Texas": {
        "Total": 88,
        "American Indian/Alaska Native": 87,
        "Asian/Pacific Islander": 94,
        "Hispanic": 84,
        "Black": 84,
        "White": 93,
        "Economically disadvantaged": 85,
        "Limited English proficiency": 59,
        "Students with disabilities": 77
    },
    "Utah": {
        "Total": 80,
        "American Indian/Alaska Native": 64,
        "Asian/Pacific Islander": 78,
        "Hispanic": 66,
        "Black": 64,
        "White": 83,
        "Economically disadvantaged": 70,
        "Limited English proficiency": 51,
        "Students with disabilities": 64
    },
    "Vermont": {
        "Total": 88,
        "American Indian/Alaska Native": 80,
        "Asian/Pacific Islander": 94,
        "Hispanic": 86,
        "Black": 72,
        "White": 88,
        "Economically disadvantaged": 77,
        "Limited English proficiency": 75,
        "Students with disabilities": 71
    },
    "Virginia": {
        "Total": 83,
        "American Indian/Alaska Native": 81,
        "Asian/Pacific Islander": 90,
        "Hispanic": 73,
        "Black": 75,
        "White": 88,
        "Economically disadvantaged": 72,
        "Limited English proficiency": 55,
        "Students with disabilities": 49
    },
    "Washington": {
        "Total": 77,
        "American Indian/Alaska Native": 59,
        "Asian/Pacific Islander": 82,
        "Hispanic": 67,
        "Black": 67,
        "White": 80,
        "Economically disadvantaged": 66,
        "Limited English proficiency": 54,
        "Students with disabilities": 58
    },
    "West Virginia": {
        "Total": 79,
        "American Indian/Alaska Native": 67,
        "Asian/Pacific Islander": 94,
        "Hispanic": 79,
        "Black": 74,
        "White": 80,
        "Economically disadvantaged": 72,
        "Limited English proficiency": 83,
        "Students with disabilities": 60
    },
    "Wisconsin": {
        "Total": 88,
        "American Indian/Alaska Native": 77,
        "Asian/Pacific Islander": 89,
        "Hispanic": 74,
        "Black": 64,
        "White": 92,
        "Economically disadvantaged": 75,
        "Limited English proficiency": 66,
        "Students with disabilities": 69
    },
    "Wyoming": {
        "Total": 79,
        "American Indian/Alaska Native": 50,
        "Asian/Pacific Islander": 86,
        "Hispanic": 67,
        "Black": 66,
        "White": 82,
        "Economically disadvantaged": 65,
        "Limited English proficiency": 56,
        "Students with disabilities": 59
    }
};
